{{- if not .Values.secretEnv.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forge.fullname" . }}
  labels:
    {{- include "forge.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  FORGE_DATABASE_DSN: {{ .Values.secretEnv.databaseDSN | quote }}
  FORGE_DATABASE_READONLY_DSN: {{ .Values.secretEnv.databaseReadOnlyDSN | quote }}
  FORGE_CRYPTO_KEY: {{ .Values.secretEnv.cryptoKey | quote }}
  FORGE_REDIS_USERNAME: {{ .Values.secretEnv.redisUsername | quote }}
  FORGE_REDIS_PASSWORD: {{ .Values.secretEnv.redisPassword | quote }}
  FORGE_KAFKA_USERNAME: {{ .Values.secretEnv.kafkaUsername | quote }}
  FORGE_KAFKA_PASSWORD: {{ .Values.secretEnv.kafkaPassword | quote }}
  FORGE_SEARCH_USERNAME: {{ .Values.secretEnv.searchUsername | quote }}
  FORGE_SEARCH_PASSWORD: {{ .Values.secretEnv.searchPassword | quote }}
  FORGE_STORAGE_ACCESS_KEY: {{ .Values.secretEnv.storageAccessKey | quote }}
  FORGE_STORAGE_SECRET_KEY: {{ .Values.secretEnv.storageSecretKey | quote }}
  FORGE_NACOS_USERNAME: {{ .Values.secretEnv.nacosUsername | quote }}
  FORGE_NACOS_PASSWORD: {{ .Values.secretEnv.nacosPassword | quote }}
  FORGE_ROCKETMQ_ACCESS_KEY: {{ .Values.secretEnv.rocketmqAccessKey | quote }}
  FORGE_ROCKETMQ_SECRET_KEY: {{ .Values.secretEnv.rocketmqSecretKey | quote }}
  FORGE_BOOTSTRAP_ADMIN: {{ .Values.secretEnv.bootstrapAdmin | quote }}
  FORGE_BOOTSTRAP_PASSWORD: {{ .Values.secretEnv.bootstrapPassword | quote }}
{{- end }}
