services:
  mail:
    image: docker.m.daocloud.io/axllent/mailpit@sha256:81370195cd4a0eab9604d17c2617a7525b0486f9365555253b6c5376c6350f1a
    environment:
      MP_MAX_MESSAGES: "100"
    ports:
      - "${FORGE_MAIL_SMTP_PORT:-1025}:1025"
      - "${FORGE_MAIL_UI_PORT:-8025}:8025"
