export const queryKeys = {
  me: ['me'] as const,
  users: ['users'] as const,
  userAssignments: (userId: string) => ['users', userId, 'assignments'] as const,
  roles: ['roles'] as const,
  permissions: ['permissions'] as const,
  menus: ['menus'] as const,
  organization: ['organization'] as const,
  departments: ['departments'] as const,
  positions: ['positions'] as const,
  userGroups: ['user-groups'] as const,
  securityConfig: ['security-config'] as const,
  sessions: ['sessions'] as const,
  auditLogs: ['audit-logs'] as const,
  apiTokens: ['api-tokens'] as const,
  mfa: ['mfa'] as const,
  approvals: ['approvals'] as const,
  temporaryRoleGrants: ['temporary-role-grants'] as const,
  accessReviews: ['access-reviews'] as const,
  systemInfo: ['system-info'] as const,
  readiness: ['readiness'] as const,
}
